### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by Jisenko** [amazeedaizee/NeedyGirlRandomizer#1]
Whenever I launch the game, there's an error that appears. I'm kinda new to this and I've tried everything I can think of.
![aaa](https://github.com/amazeedaizee/NeedyGirlRandomizer/assets/153269754/a2bfa03b-74db-4372-ac42-a6d22747e8fd)
The settings don't seem to change anything either. Other than that, the mod does randomize stats, but that seems to be it.

This is my first time reaching out for help in github, so if I missed something, please tell me. Thank you!

**Comment by amazeedaizee** [comment]
Hello, here's a zip with an updated version of the dll, just replace the one in the folder with the one in the zip. Please let me know if it works!

[Randomizer_dll_2.0.0.1_beta.zip](https://github.com/amazeedaizee/NeedyGirlRandomizer/files/15410351/Randomizer_dll_2.0.0.1_beta.zip)

**Comment by Jisenko** [comment]
So, I moved the updated dll file into the folder and replaced the old one, but unfortunately the same problem persists.
It's also the same error.

**Comment by amazeedaizee** [comment]
Ok I see where the problem is. one assembly probably had that method stripped (it was there previously but now it doesn't). Here's the assembly needed to load the settings:

[Newtonsoft.Json.zip](https://github.com/amazeedaizee/NeedyGirlRandomizer/files/15410715/Newtonsoft.Json.zip)

Edit: Place this in the mod folder with both the mod dll and the settings exe.

**Comment by Jisenko** [comment]
Sorry for the late response - I put the new file into the folder as you asked, but the same problem shows up with the same error. If it might change anything, I'll also mention that I'm using the special version, but the normal version still came up with the error.

![image](https://github.com/amazeedaizee/NeedyGirlRandomizer/assets/153269754/b00fdb33-0a1c-4d15-9fe1-370699bb41fb)

**Comment by amazeedaizee** [comment]
Oh sorry! I mistakenly sent in the stripped version.

Here's the right one: 
[Newtonsoft.Json.zip](https://github.com/amazeedaizee/NeedyGirlRandomizer/files/15411428/Newtonsoft.Json.zip)

**Comment by Jisenko** [comment]
Unfortunately, it still comes up with the same result.

Edit: The randomizer.initializer line did change though.

![image](https://github.com/amazeedaizee/NeedyGirlRandomizer/assets/153269754/ca8b499b-358e-446d-a73d-42336d28be90)

**Comment by amazeedaizee** [comment]
Hmm, that's pretty odd. The Newtonsoft.Json.dll is the same one used to compile the mod.

Here's a re-compiled and clean version of the dll of the mod (also on a newer framework):
[Randomizer_test.zip](https://github.com/amazeedaizee/NeedyGirlRandomizer/files/15411763/Randomizer_test.zip)

If it doesn't work, I'll try and look more into this for any possible solutions.

**Comment by Jisenko** [comment]
It still doesn't work, but the error slightly changed again.

![image](https://github.com/amazeedaizee/NeedyGirlRandomizer/assets/153269754/59763e1f-a6ca-4568-894f-34dc81f9f1a8)

**Comment by amazeedaizee** [comment]
Can you try placing the unstripped Newtonsoft.Json file into the unstripped_corlib folder, and let me know what happens?

**Comment by Jisenko** [comment]
It works!! Thank you!!
